import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { SeedNetworkButton } from "@/features/dev/SeedNetworkButton";
export function HomePage() {
    return (_jsxs("div", { className: "w-full space-y-8 px-4 lg:px-6 py-6", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("h1", { className: "text-3xl font-semibold", children: "rProtocols" }), _jsx(SeedNetworkButton, {})] }), _jsxs("p", { className: "text-gray-700 w-full", children: ["rProtocols are open, living agreements for how we collaborate and build together. Each protocol is linked to a human ", _jsx("strong", { children: "Need" }), " \u2014 a question about how we can serve life better \u2014 and grouped into ", _jsx("strong", { children: "Suites" }), " that connect related practices."] }), _jsx("div", { className: "grid gap-6 sm:grid-cols-3 mt-8", children: [
                    { to: "/collaboration", title: "Collaboration Protocols", desc: "How open collaboration works." },
                    { to: "/work", title: "Work Protocols", desc: "How we collaborate in work." },
                    { to: "/website", title: "Website Protocols", desc: "How we share and communicate online." },
                ].map(({ to, title, desc }) => (_jsxs(Link, { to: to, className: "rounded-2xl border p-5 shadow-sm hover:shadow-md transition bg-white", children: [_jsx("h2", { className: "text-xl font-semibold mb-2", children: title }), _jsx("p", { className: "text-gray-600", children: desc })] }, to))) }), _jsxs("section", { className: "mt-10", children: [_jsx("h2", { className: "text-2xl font-semibold", children: "How It Works" }), _jsxs("p", { className: "text-gray-700 mt-2 w-full", children: ["Each ", _jsx("strong", { children: "Need" }), " asks a question about collaboration or life. Each ", _jsx("strong", { children: "Protocol" }), " offers an experimental answer.", _jsx("strong", { children: " Suites" }), " group related protocols together, making it easier to find patterns that work in different contexts."] })] })] }));
}
